---
server:
  shutdown: graceful

spring:
  application:
    name: Spring-Boot-Redis
  data:
    redis:
      host: localhost
      port: 6379
  main:
    banner-mode: off

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
